/*
 * static_model.h
 *
 * automatically generated from src/scl/IED_GEN.icd
 */

#ifndef GEN1_STATIC_MODEL_H_
#define GEN1_STATIC_MODEL_H_

#include <stdlib.h>
#include "iec61850_model.h"

extern IedModel GEN1_iedModel;
extern LogicalDevice GEN1_iedModel_GEN1;
extern LogicalNode   GEN1_iedModel_GEN1_LLN0;
extern DataObject    GEN1_iedModel_GEN1_LLN0_Mod;
extern DataAttribute GEN1_iedModel_GEN1_LLN0_Mod_stVal;
extern DataAttribute GEN1_iedModel_GEN1_LLN0_Mod_q;
extern DataAttribute GEN1_iedModel_GEN1_LLN0_Mod_t;
extern LogicalNode   GEN1_iedModel_GEN1_MMXU1;
extern DataObject    GEN1_iedModel_GEN1_MMXU1_PhV;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsA;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsA_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsA_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsA_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsA_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsB;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsB_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsB_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsB_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsB_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsC;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsC_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsC_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsC_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_phsC_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_neut;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_neut_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_neut_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_neut_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_neut_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_PhV_t;
extern DataObject    GEN1_iedModel_GEN1_MMXU1_A;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsA;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsA_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsA_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsA_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsA_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsB;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsB_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsB_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsB_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsB_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsC;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsC_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsC_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsC_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_phsC_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_neut;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_neut_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_neut_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_neut_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_neut_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_A_t;
extern DataObject    GEN1_iedModel_GEN1_MMXU1_Hz;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_Hz_instMag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_Hz_instMag_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_Hz_instMag_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_Hz_instMag_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_Hz_instMag_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_Hz_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_Hz_t;
extern DataObject    GEN1_iedModel_GEN1_MMXU1_TotW;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_TotW_instMag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_TotW_instMag_mag;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_TotW_instMag_mag_f;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_TotW_instMag_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_TotW_instMag_t;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_TotW_q;
extern DataAttribute GEN1_iedModel_GEN1_MMXU1_TotW_t;



#define GEN1_IEDMODEL_GEN1 (&GEN1_iedModel_GEN1)
#define GEN1_IEDMODEL_GEN1_LLN0 (&GEN1_iedModel_GEN1_LLN0)
#define GEN1_IEDMODEL_GEN1_LLN0_Mod (&GEN1_iedModel_GEN1_LLN0_Mod)
#define GEN1_IEDMODEL_GEN1_LLN0_Mod_stVal (&GEN1_iedModel_GEN1_LLN0_Mod_stVal)
#define GEN1_IEDMODEL_GEN1_LLN0_Mod_q (&GEN1_iedModel_GEN1_LLN0_Mod_q)
#define GEN1_IEDMODEL_GEN1_LLN0_Mod_t (&GEN1_iedModel_GEN1_LLN0_Mod_t)
#define GEN1_IEDMODEL_GEN1_MMXU1 (&GEN1_iedModel_GEN1_MMXU1)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV (&GEN1_iedModel_GEN1_MMXU1_PhV)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsA (&GEN1_iedModel_GEN1_MMXU1_PhV_phsA)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsA_mag (&GEN1_iedModel_GEN1_MMXU1_PhV_phsA_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsA_mag_f (&GEN1_iedModel_GEN1_MMXU1_PhV_phsA_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsA_q (&GEN1_iedModel_GEN1_MMXU1_PhV_phsA_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsA_t (&GEN1_iedModel_GEN1_MMXU1_PhV_phsA_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsB (&GEN1_iedModel_GEN1_MMXU1_PhV_phsB)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsB_mag (&GEN1_iedModel_GEN1_MMXU1_PhV_phsB_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsB_mag_f (&GEN1_iedModel_GEN1_MMXU1_PhV_phsB_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsB_q (&GEN1_iedModel_GEN1_MMXU1_PhV_phsB_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsB_t (&GEN1_iedModel_GEN1_MMXU1_PhV_phsB_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsC (&GEN1_iedModel_GEN1_MMXU1_PhV_phsC)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsC_mag (&GEN1_iedModel_GEN1_MMXU1_PhV_phsC_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsC_mag_f (&GEN1_iedModel_GEN1_MMXU1_PhV_phsC_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsC_q (&GEN1_iedModel_GEN1_MMXU1_PhV_phsC_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_phsC_t (&GEN1_iedModel_GEN1_MMXU1_PhV_phsC_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_neut (&GEN1_iedModel_GEN1_MMXU1_PhV_neut)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_neut_mag (&GEN1_iedModel_GEN1_MMXU1_PhV_neut_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_neut_mag_f (&GEN1_iedModel_GEN1_MMXU1_PhV_neut_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_neut_q (&GEN1_iedModel_GEN1_MMXU1_PhV_neut_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_neut_t (&GEN1_iedModel_GEN1_MMXU1_PhV_neut_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_q (&GEN1_iedModel_GEN1_MMXU1_PhV_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_PhV_t (&GEN1_iedModel_GEN1_MMXU1_PhV_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_A (&GEN1_iedModel_GEN1_MMXU1_A)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsA (&GEN1_iedModel_GEN1_MMXU1_A_phsA)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsA_mag (&GEN1_iedModel_GEN1_MMXU1_A_phsA_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsA_mag_f (&GEN1_iedModel_GEN1_MMXU1_A_phsA_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsA_q (&GEN1_iedModel_GEN1_MMXU1_A_phsA_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsA_t (&GEN1_iedModel_GEN1_MMXU1_A_phsA_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsB (&GEN1_iedModel_GEN1_MMXU1_A_phsB)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsB_mag (&GEN1_iedModel_GEN1_MMXU1_A_phsB_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsB_mag_f (&GEN1_iedModel_GEN1_MMXU1_A_phsB_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsB_q (&GEN1_iedModel_GEN1_MMXU1_A_phsB_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsB_t (&GEN1_iedModel_GEN1_MMXU1_A_phsB_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsC (&GEN1_iedModel_GEN1_MMXU1_A_phsC)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsC_mag (&GEN1_iedModel_GEN1_MMXU1_A_phsC_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsC_mag_f (&GEN1_iedModel_GEN1_MMXU1_A_phsC_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsC_q (&GEN1_iedModel_GEN1_MMXU1_A_phsC_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_phsC_t (&GEN1_iedModel_GEN1_MMXU1_A_phsC_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_neut (&GEN1_iedModel_GEN1_MMXU1_A_neut)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_neut_mag (&GEN1_iedModel_GEN1_MMXU1_A_neut_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_neut_mag_f (&GEN1_iedModel_GEN1_MMXU1_A_neut_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_neut_q (&GEN1_iedModel_GEN1_MMXU1_A_neut_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_neut_t (&GEN1_iedModel_GEN1_MMXU1_A_neut_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_q (&GEN1_iedModel_GEN1_MMXU1_A_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_A_t (&GEN1_iedModel_GEN1_MMXU1_A_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_Hz (&GEN1_iedModel_GEN1_MMXU1_Hz)
#define GEN1_IEDMODEL_GEN1_MMXU1_Hz_instMag (&GEN1_iedModel_GEN1_MMXU1_Hz_instMag)
#define GEN1_IEDMODEL_GEN1_MMXU1_Hz_instMag_mag (&GEN1_iedModel_GEN1_MMXU1_Hz_instMag_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_Hz_instMag_mag_f (&GEN1_iedModel_GEN1_MMXU1_Hz_instMag_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_Hz_instMag_q (&GEN1_iedModel_GEN1_MMXU1_Hz_instMag_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_Hz_instMag_t (&GEN1_iedModel_GEN1_MMXU1_Hz_instMag_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_Hz_q (&GEN1_iedModel_GEN1_MMXU1_Hz_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_Hz_t (&GEN1_iedModel_GEN1_MMXU1_Hz_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_TotW (&GEN1_iedModel_GEN1_MMXU1_TotW)
#define GEN1_IEDMODEL_GEN1_MMXU1_TotW_instMag (&GEN1_iedModel_GEN1_MMXU1_TotW_instMag)
#define GEN1_IEDMODEL_GEN1_MMXU1_TotW_instMag_mag (&GEN1_iedModel_GEN1_MMXU1_TotW_instMag_mag)
#define GEN1_IEDMODEL_GEN1_MMXU1_TotW_instMag_mag_f (&GEN1_iedModel_GEN1_MMXU1_TotW_instMag_mag_f)
#define GEN1_IEDMODEL_GEN1_MMXU1_TotW_instMag_q (&GEN1_iedModel_GEN1_MMXU1_TotW_instMag_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_TotW_instMag_t (&GEN1_iedModel_GEN1_MMXU1_TotW_instMag_t)
#define GEN1_IEDMODEL_GEN1_MMXU1_TotW_q (&GEN1_iedModel_GEN1_MMXU1_TotW_q)
#define GEN1_IEDMODEL_GEN1_MMXU1_TotW_t (&GEN1_iedModel_GEN1_MMXU1_TotW_t)

#endif /* STATIC_MODEL_H_ */

